### ISSUE TITLE
babel-root-import doesn't play well with iOS builds

### ISSUE THREAD

**Issue by Micjoyce** [Astrocoders/astroapp-rn-boilerplate#4]
I clone this repo and npm install / react-native-link / react-native run-ios and got this error.
![1](https://cloud.githubusercontent.com/assets/4250838/20034744/4400bae8-a404-11e6-988b-ef42c3e447ec.png)

how can I fixed this Error?

**Comment by fakenickels** [comment]
That's odd! But seems that babel-root-import isn't working well for you, the path have a duplicated like this `src/src`. I just updated the hyper-clean script can you clone the repo again and run `npm run hyper-clean`? So it will get you a fresh setup again.
But remember of installing `npm i -g yarn` first!

**Comment by Micjoyce** [comment]
I clone this repo again and  run npm i -g 
cd astro-meteor-served-rn-boilerplate
yarn
npm run hyper-clean 
and them get this error.
It seems that babel-root-import isn't working well.

node version  6.2.0
npm version 3.8.9
yarn version 0.16.1

`> AstroApp@0.0.1 hyper-clean /Users/michaelxu/learn-project/rn-demo/astro-meteor-served-rn-boilerplate

> npm run warning-clean-up && npm run ios:clean && rm -rf $TMPDIR/react-\* && npm run reinstall-npm-modules && npm run android:gradle-clean && react-native link
> 
> AstroApp@0.0.1 warning-clean-up /Users/michaelxu/learn-project/rn-demo/astro-meteor-served-rn-boilerplate
> echo '\033[1;33m Please, uninstall the app from your phone or destroy the emulator
> \033[0m'

 Please, uninstall the app from your phone or destroy the emulator

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ios:clean"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9

npm ERR! missing script: ios:clean
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michaelxu/learn-project/rn-demo/astro-meteor-served-rn-boilerplate/npm-debug.log

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "hyper-clean"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! AstroApp@0.0.1 hyper-clean: `npm run warning-clean-up && npm run ios:clean && rm -rf $TMPDIR/react-* && npm run reinstall-npm-modules && npm run android:gradle-clean && react-native link`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the AstroApp@0.0.1 hyper-clean script 'npm run warning-clean-up && npm run ios:clean && rm -rf $TMPDIR/react-\* && npm run reinstall-npm-modules && npm run android:gradle-clean && react-native link'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the AstroApp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run warning-clean-up && npm run ios:clean && rm -rf $TMPDIR/react-\* && npm run reinstall-npm-modules && npm run android:gradle-clean && react-native link
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs AstroApp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls AstroApp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michaelxu/learn-project/rn-demo/astro-meteor-served-rn-boilerplate/npm-debug.log`

**Comment by fakenickels** [comment]
Ok, my bad here! I did a typo in the script, I just fixed. You can re-clone and try running `npm run hyper-clean` again.

**Comment by Micjoyce** [comment]
the `watchman:clear` shoud be  `clear:watchman`.😄

**Comment by Micjoyce** [comment]
I think babel-root-import isn't work well for react-native.
https://github.com/michaelzoidl/babel-root-import/issues/56

**Comment by fakenickels** [comment]
I think that there is a problem there for iOS, because it works fine with Android.
But thanks for pointing it out, I'm going to see why it just works with Android.

**Comment by fakenickels** [comment]
Fixed in https://github.com/Astrocoders/astro-meteor-served-rn-boilerplate/commit/485bc73906f0d008b34d96aa51242ce72913261a
